// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ladder rung: bitrate and channel count.
 */
export type AudioRung = { bps: bigint, channels: number, };
