// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The byte numbers a resolved preset gives the planner, named as in
 * `cia_core::ResolvedLimit` (`hard_for` / `budget_for` / `safety_for` for the
 * video kind).
 *
 * The planner aims at `raw_budget_bytes`: the preset limit with
 * `safety_bytes` already taken off. DESIGN 3.5 calls this number `hard_bytes`
 * and subtracts one more byte; see docs/DECISIONS.md.
 */
export type Budget = { 
/**
 * What the planner aims at; the output must be at most this.
 */
raw_budget_bytes: bigint, 
/**
 * The service's stated limit for one file.
 */
hard_bytes: bigint, safety_bytes: bigint, };
