// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Container } from "./Container";

export type Decision = { "type": "keep_original" } | { "type": "remux", container: Container, } | { "type": "encode" };
