// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the video will be encoded; decides the margin and the retry factor.
 */
export type EncoderKind = "two_pass_software" | "single_pass_hardware" | "web_codecs";
