// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefusalCode } from "./RefusalCode";
import type { Suggestion } from "./Suggestion";

/**
 * Why no plan exists. `code` is `TooLongForLimit` when a shorter clip would
 * fit (with a `Trim` suggestion), `BelowQualityFloor` when not even one
 * second fits, `UnsupportedInput` for a probe with no duration or size.
 */
export type PlanRefusal = { code: RefusalCode, suggestions: Array<Suggestion>, };
