// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTrackChoice } from "./AudioTrackChoice";
import type { FrameRatePref } from "./FrameRatePref";

/**
 * User choices from the Advanced drawer that change the plan.
 */
export type PlanOptions = { audio: AudioTrackChoice, frame_rate_pref: FrameRatePref, 
/**
 * `(start_ms, end_ms)` in source time; the plan covers only this range.
 */
trim: [number, number] | null, };
