// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefusalCode = { "type": "too_long_for_limit", max_duration_ms: bigint, } | { "type": "below_quality_floor" } | { "type": "cannot_shrink_type" } | { "type": "too_many_files_for_message", max: number, } | { "type": "total_too_big" } | { "type": "needs_ffmpeg" } | { "type": "browser_lacks_codec", codec: string, } | { "type": "unsupported_input", what: string, } | { "type": "encrypted" };
