// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One output size and frame rate the planner may choose.
 */
export type Rung = { width: number, height: number, fps: number, };
