// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lossy formats of the standalone audio planner (3.6 table).
 */
export type StandaloneAudioFormat = "mp3" | "aac" | "opus";
