// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Suggestion = { "type": "trim", max_duration_ms: bigint, } | { "type": "pick_preset", preset_id: string, predicted_bytes: bigint, } | { "type": "split_into_messages", groups: Array<Array<string>>, } | { "type": "remove_files", item_ids: Array<string>, } | { "type": "install_ffmpeg" } | { "type": "use_desktop_app" } | { "type": "use_other_browser", browser: string, };
