// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCodec } from "./AudioCodec";
import type { Container } from "./Container";
import type { VideoCaps } from "./VideoCaps";
import type { VideoCodec } from "./VideoCodec";

/**
 * What the preset accepts: container, codecs and size/frame-rate caps.
 */
export type Target = { container: Container, video_codec: VideoCodec, audio_codec: AudioCodec, caps: VideoCaps, };
