// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTrack } from "./AudioTrack";

/**
 * Everything the planner needs to know about the input.
 */
export type VideoProbe = { duration_ms: bigint, 
/**
 * Lower-case container token: "mp4", "mov", "mkv", "webm", "avi"...
 */
container: string, 
/**
 * Lower-case codec token: "h264", "hevc", "vp9", "av1", "prores"...
 */
video_codec: string, coded_w: number, coded_h: number, 
/**
 * Display size after the rotation in the display matrix has been applied.
 */
display_w: number, display_h: number, rotation_degrees: number, avg_fps: number, max_fps: number, 
/**
 * More than 2 percent spread in packet durations over the first 5 s.
 */
is_vfr: boolean, pixel_format: string, color_transfer: string, color_primaries: string, 
/**
 * Transfer `smpte2084` (PQ) or `arib-std-b67` (HLG).
 */
is_hdr: boolean, dolby_vision_profile: number | null, audio: Array<AudioTrack>, };
