import { useMemo, useState } from "react";
import { useStore } from "../state/store";
import { Modal } from "./primitives";

export interface LicenseEntry {
  name: string;
  version?: string;
  license: string;
  copyright?: string;
  url?: string;
  text?: string;
  note?: string;
}
export interface LicensesData {
  generated_at: string;
  groups: { title: string; entries: LicenseEntry[] }[];
}

/** The data file is generated by `cargo xtask licenses` into packages/licenses-data/licenses.json. */
export default function LicensesPage({ data }: { data: LicensesData }) {
  const { dispatch } = useStore();
  const [q, setQ] = useState("");
  const [open, setOpen] = useState<string | null>(null);
  const groups = useMemo(() => data.groups.map((g) => ({ ...g, entries: g.entries.filter((e) => !q || `${e.name} ${e.license}`.toLowerCase().includes(q.toLowerCase())) })).filter((g) => g.entries.length), [data, q]);
  return (
    <Modal title="Licenses" onClose={() => dispatch({ type: "modal", modal: "settings", section: "about" })} width={760} testId="licenses">
      <input className="smg-input mb-4 w-full" placeholder="Search" value={q} onChange={(e) => setQ(e.target.value)} aria-label="Search licenses" />
      <div className="flex max-h-[60vh] flex-col gap-5 overflow-auto pr-1">
        {groups.map((g) => (
          <section key={g.title}>
            <h3 className="smg-label mb-2">{g.title}</h3>
            <ul className="flex flex-col gap-1">
              {g.entries.map((e) => {
                const key = `${g.title}/${e.name}`;
                return (
                  <li key={key} className="rounded-card border border-subtle bg-surface-card px-3 py-2">
                    <button className="flex w-full items-center justify-between gap-3 text-left" onClick={() => setOpen(open === key ? null : key)} aria-expanded={open === key}>
                      <span><span className="font-medium">{e.name}</span>{e.version && <span className="text-on-surface-muted"> {e.version}</span>}</span>
                      <span className="text-xs text-on-surface-muted">{e.license}</span>
                    </button>
                    {open === key && (
                      <div className="mt-2 text-xs text-on-surface-muted">
                        {e.copyright && <p className="m-0">{e.copyright}</p>}
                        {e.note && <p className="m-0">{e.note}</p>}
                        {e.url && <p className="m-0"><a className="underline" href={e.url} target="_blank" rel="noreferrer">{e.url}</a></p>}
                        {e.text && <pre className="mt-2 max-h-60 overflow-auto whitespace-pre-wrap font-sans">{e.text}</pre>}
                      </div>
                    )}
                  </li>
                );
              })}
            </ul>
          </section>
        ))}
        <p className="text-xs text-on-surface-subtle">Generated {data.generated_at}.</p>
      </div>
    </Modal>
  );
}
