// Generates src/theme.css from tokens.ts so CSS and TS can never drift.
import { writeFileSync } from "node:fs";
import { themeTokens } from "../dist/tokens.js";
const block = (sel, t) => `${sel} {\n${Object.entries(t).map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}\n`;
const css = `/* GENERATED by scripts/gen-css.mjs from src/tokens.ts. Do not edit. */\n` +
  block(":root, .theme-light", themeTokens.light) + block(".theme-dark", themeTokens.dark);
writeFileSync(new URL("../src/theme.css", import.meta.url), css);
console.log("wrote src/theme.css");
