//! `cargo xtask <task>`: repo chores that need no extra tooling.
//!   types        write ts-rs bindings to packages/engine-client/src/generated
//!   presets-doc  write docs/presets-sources.md from packages/presets/presets.json
//!   fixtures     generate fixtures/synth (uses ffmpeg on PATH for video)
//!   wasm         build crates/cia-wasm for the web app (wasm-bindgen + wasm-opt)
//!   licenses     regenerate packages/licenses-data/licenses.json
//!   keygen       print a new Ed25519 keypair (license or manifest signing)
use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("types") => types(),
        Some("presets-doc") => presets_doc(),
        Some("fixtures") => fixtures(&args[1..]),
        Some("wasm") => wasm(&args[1..]),
        Some("licenses") => licenses(),
        Some("keygen") => keygen(),
        _ => {
            eprintln!("usage: cargo xtask <types|presets-doc|fixtures|wasm|licenses|keygen>");
            std::process::exit(2);
        }
    }
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().with_context(|| format!("running {:?}", cmd))?;
    if !status.success() {
        bail!("{:?} failed with {status}", cmd);
    }
    Ok(())
}

/// ts-rs writes bindings during `cargo test`; TS_RS_EXPORT_DIR points it at the package.
fn types() -> Result<()> {
    let out = root().join("packages/engine-client/src/generated");
    std::fs::create_dir_all(&out)?;
    for entry in std::fs::read_dir(&out)? {
        let p = entry?.path();
        if p.extension().is_some_and(|e| e == "ts") {
            std::fs::remove_file(p)?;
        }
    }
    run(Command::new("cargo")
        .current_dir(root())
        .env("TS_RS_EXPORT_DIR", &out)
        .args([
            "test",
            "-p",
            "cia-core",
            "-p",
            "cia-video-plan",
            "--",
            "export_bindings",
        ])
        .arg("--quiet"))?;
    // index.ts re-exports every generated file
    let mut names: Vec<String> = std::fs::read_dir(&out)?
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| n.ends_with(".ts") && n != "index.ts")
        .map(|n| n.trim_end_matches(".ts").to_string())
        .collect();
    names.sort();
    let index = String::from("// GENERATED by `cargo xtask types`. Do not edit.\n")
        + &names
            .iter()
            .map(|n| format!("export type {{ {n} }} from \"./{n}\";\n"))
            .collect::<String>();
    std::fs::write(out.join("index.ts"), index)?;
    println!("wrote {} bindings to {}", names.len(), out.display());
    Ok(())
}

fn presets_doc() -> Result<()> {
    let json: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(
        root().join("packages/presets/presets.json"),
    )?)?;
    let mut md = String::from("# Preset limits and their sources\n\nGenerated by `cargo xtask presets-doc` from `packages/presets/presets.json`. Do not edit by hand.\n\n| Preset | Limit | Scope | Counts | Safety | Confidence | Checked | Sources |\n|---|---|---|---|---|---|---|---|\n");
    for p in json["presets"].as_array().unwrap() {
        let name = format!(
            "{}{}",
            p["tile_label"].as_str().unwrap(),
            p["tier_label"]
                .as_str()
                .map(|t| format!(" / {t}"))
                .unwrap_or_default()
        );
        let (limit, scope, counts, safety) = match p.get("limit") {
            Some(l) => (
                format!(
                    "{} ({} bytes)",
                    l["stated_as"].as_str().unwrap(),
                    l["bytes"]
                ),
                l["scope"].as_str().unwrap().to_string(),
                l["counts"].as_str().unwrap().to_string(),
                l["safety_bytes"].to_string(),
            ),
            None => ("none".into(), "".into(), "".into(), "".into()),
        };
        let (conf, checked, urls) = match p.get("source") {
            Some(s) => (
                s["confidence"].as_str().unwrap().to_string(),
                s["checked_on"].as_str().unwrap().to_string(),
                s["urls"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|u| format!("<{}>", u.as_str().unwrap()))
                    .collect::<Vec<_>>()
                    .join(" "),
            ),
            None => ("".into(), "".into(), "".into()),
        };
        md.push_str(&format!(
            "| {name} | {limit} | {scope} | {counts} | {safety} | {conf} | {checked} | {urls} |\n"
        ));
        if let Some(n) = p["source"]["note"].as_str() {
            md.push_str(&format!("| | | | | | | | {n} |\n"));
        }
    }
    std::fs::write(root().join("docs/presets-sources.md"), md)?;
    println!("wrote docs/presets-sources.md");
    Ok(())
}

fn fixtures(args: &[String]) -> Result<()> {
    let mut cmd = Command::new("python3");
    cmd.current_dir(root())
        .arg("tools/fixtures/generate.py")
        .args(args);
    run(&mut cmd)
}

/// Builds only `-p cia-wasm`: the workspace also holds `cia-desktop`, whose
/// Tauri build needs the GTK/WebKit dev packages the wasm CI job does not have,
/// so nothing here may build or test the whole workspace.
fn wasm(args: &[String]) -> Result<()> {
    let script = root().join("tools/build-wasm.sh");
    if script.exists() {
        let mut cmd = Command::new("bash");
        cmd.current_dir(root()).arg(script).args(args);
        return run(&mut cmd);
    }
    run(Command::new("cargo").current_dir(root()).args([
        "build",
        "-p",
        "cia-wasm",
        "--target",
        "wasm32-unknown-unknown",
        "--release",
    ]))
}

fn licenses() -> Result<()> {
    let mut cmd = Command::new("bash");
    cmd.current_dir(root()).arg("tools/licenses/generate.sh");
    run(&mut cmd)
}

fn keygen() -> Result<()> {
    run(Command::new("cargo").current_dir(root()).args([
        "run",
        "--quiet",
        "-p",
        "cia-license",
        "--features",
        "keygen",
        "--bin",
        "cia-keygen",
    ]))
}
