// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputLocation } from "./OutputLocation";
import type { QualityLabel } from "./QualityLabel";
import type { VerificationReport } from "./VerificationReport";

export type Artifact = { id: string, item_id: string, location: OutputLocation, file_name: string, bytes: bigint, 
/**
 * "jpeg", "mp4", "zip" ...
 */
format: string, summary: string, quality: QualityLabel | null, verification: VerificationReport, };
