// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttemptVerdict = { "type": "fits" } | { "type": "over", by_bytes: bigint, } | { "type": "below_floor" } | { "type": "error", message: string, } | { "type": "cancelled" };
