// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioStreamInfo = { index: number, codec: string, channels: number, sample_rate: number, bitrate_bps: bigint | null, title: string | null, };
