// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfmpegCapabilities } from "./FfmpegCapabilities";
import type { WebCapabilities } from "./WebCapabilities";

/**
 * What a host can do (DESIGN.md 2.7). Filled by each host.
 */
export type Capabilities = { host: string, ffmpeg: FfmpegCapabilities | null, web: WebCapabilities | null, can_copy_files: boolean, can_drag_out: boolean, can_reveal: boolean, can_choose_folder: boolean, heic_input: boolean, avif_input: boolean, opus_encode: boolean, mp3_encode: boolean, aac_encode: boolean, video: boolean, };
