// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Failure = { 
/**
 * Stable code for logs: "damaged_input", "encoder_crash", "disk_full", "not_writable", "source_vanished", "over_after_retries".
 */
code: string, message: string, closest_bytes: bigint | null, };
