// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";
import type { KindDetail } from "./KindDetail";
import type { SourceRef } from "./SourceRef";

export type InputItem = { id: string, source: SourceRef, 
/**
 * Path relative to the dropped folder, or just the file name.
 */
rel_path: string, bytes: bigint, kind: Kind, detail: KindDetail, 
/**
 * Set when the item came from a dropped folder; the folder's display name.
 */
folder: string | null, };
