// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";
import type { Failure } from "./Failure";
import type { Refusal } from "./Refusal";

export type ItemOutcome = { "type": "fitted", artifact: Artifact, } | { "type": "kept_original", artifact: Artifact, } | { "type": "refused", refusal: Refusal, } | { "type": "failed", failure: Failure, } | { "type": "cancelled" };
