// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputLocation = { "type": "path", path: string, } | { "type": "opfs", path: string, };
