// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Packaging } from "./Packaging";

export type PackagingPlan = { "type": "separate_files" } | { "type": "archive", format: Packaging, file_name: string, overhead_bytes: bigint, };
