// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Packaging = "auto" | "separate_files" | "zip" | "seven_zip" | "tar_zst" | "tar_xz";
