// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoFormat } from "./VideoFormat";

export type PresetFormats = { image: Array<string>, animated: Array<string>, video: Array<VideoFormat>, audio: Array<string>, document: string, };
