// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountsAs } from "./CountsAs";
import type { LimitScope } from "./LimitScope";

export type PresetLimit = { bytes: bigint, stated_as: string, scope: LimitScope, counts: CountsAs, safety_bytes: bigint, };
