// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetFormats } from "./PresetFormats";
import type { PresetLimit } from "./PresetLimit";
import type { PresetMode } from "./PresetMode";
import type { PresetSource } from "./PresetSource";
import type { VideoCaps } from "./VideoCaps";

export type Preset = { id: string, group: string, tile_label: string, tier_label: string | null, tier_summary: string | null, output_label: string, icon: string, order: number, mode: PresetMode, default_tier: boolean, note: string | null, limit: PresetLimit | null, limit_by_kind: Record<string, PresetLimit>, max_files_per_message: number | null, formats: PresetFormats, video_caps: VideoCaps, source: PresetSource | null, };
