// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitScope } from "./LimitScope";

/**
 * A preset (or Custom) resolved into byte numbers the engine aims at.
 */
export type ResolvedLimit = { 
/**
 * Output (or output total) MUST be strictly less than this.
 */
hard_bytes: bigint, 
/**
 * What the engine aims at after encoding overhead and the safety margin.
 */
raw_budget_bytes: bigint, safety_bytes: bigint, scope: LimitScope, max_files_per_message: number | null, by_kind: Record<string, ResolvedKindLimit>, 
/**
 * Human label used in file names: "Discord", "Email", "Custom 8 MB".
 */
output_label: string, 
/**
 * Shown in copy: "20 MB", "18 MB of attachments".
 */
stated_label: string, };
