// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerificationReport = { size_ok: boolean, decodes: boolean, checks: Array<string>, failures: Array<string>, };
