// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTrackChoice } from "./AudioTrackChoice";
import type { FrameRatePref } from "./FrameRatePref";
import type { VideoFormatPref } from "./VideoFormatPref";

export type VideoOptions = { format: VideoFormatPref, 
/**
 * "Faster (uses your graphics card)". Default on.
 */
faster: boolean, audio: AudioTrackChoice, frame_rate: FrameRatePref, 
/**
 * Trim range in ms, applied per item by id.
 */
trims: Record<string, [number, number]>, };
