// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebCapabilities = { cross_origin_isolated: boolean, webcodecs: boolean, h264_encode: boolean, vp9_encode: boolean, aac_encode: boolean, opus_encode: boolean, hdr_verified: boolean, directory_picker: boolean, opfs: boolean, browser: string, };
